# Generated by Django 2.0.7 on 2018-07-17 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestbook', '0002_guestbook_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestbook',
            name='time',
            field=models.TimeField(),
        ),
    ]
