# Generated by Django 2.0.7 on 2018-07-17 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestbook', '0003_auto_20180717_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestbook',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
